# -*- coding: utf-8 -*-
"""breast_cancer_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EicqMfSMFX7cZbI3msZ6OWi7J_0iK2ca
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, roc_curve, roc_auc_score

url = "https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data"

df = pd.read_csv(url, header=None)

df.head()

print("Dataset shape:", df.shape)

print("\nFirst 5 diagnosis labels:")
print(df[1].head())

print("\nUnique diagnosis values:")
print(df[1].unique())

'''
confirmed:
✅ Dataset has 569 total cases
✅ Labels are binary (M/B)
✅ supervised learning classification

'''

# Features = all columns except ID and diagnosis
X = df.drop(columns=[0, 1])

# Target = diagnosis column
y = df[1]

# Convert labels to numbers , Machine learning models usually work better with numbers than letters.
y = y.map({'M': 1, 'B': 0})

print("X shape:", X.shape)
print("y shape:", y.shape)
print("\nFirst 5 labels:")
print(y.head())

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training set:", X_train.shape)
print("Testing set :", X_test.shape)


# random_state=42, Keeps split reproducible, stratify=y, Preserves class balance

# Feature Scaling-Since we have different ranges (area, radius, smoothness)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaled training shape:", X_train_scaled.shape)
print("Scaled testing shape :", X_test_scaled.shape)